export enum UserProperty {
  id = 'id',
  _id = '_id',
  email = 'email',
  password = 'password',
  username = 'username',
  firstName = 'firstName',
  lastName = 'lastName',
  gender = 'gender',
  imageURL = 'imageURL',
  newsletter = 'newsletter',
  isAdmin = 'isAdmin',
  userChannelLastMessageSeen = 'userChannelLastMessageSeen',
  completedCourseIds = 'completedCourseIds',
  completedModuleIds = 'completedModuleIds',
  completedLectureIds = 'completedLectureIds',
}
